// src/Helix/ClientApp/src/components/layouts/main-layout.tsx
import AppConversation from "../organisms/app-conversation"
import AppSidebar from "../organisms/app-sidebar"
import { SidebarProvider, SidebarTrigger } from "../ui/sidebar"

export default function MainLayout() {
  return (
    <SidebarProvider>
      <AppSidebar />
      <main className="flex-1 flex-col relative">
        <div className="absolute left-2 top-2">
          <SidebarTrigger />
        </div>
        <AppConversation />
      </main>
    </SidebarProvider>
  )
}

// src/Helix/ClientApp/src/components/layout/MainLayout.vue
<script setup lang="ts">
import {
  SidebarProvider,
} from "@/components/ui/sidebar";
import ConversationSidebar from "./ConversationSidebar.vue";
</script>

<template>
  <SidebarProvider>
    <ConversationSidebar />
    <main class="flex flex-1 flex-col gap-4 p-4">
      <slot />
    </main>
  </SidebarProvider>
</template>
